server:
  port: 8000

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
      routes:
        - id: foo-service
          uri: lb://FOO-SERVICE
          predicates:
            - Path=/foo/**
            - Method=GET,POST
          filters:
            - RewritePath=/foo/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace,busrefresh, info, prometheus, metrics