server:
  port: 8000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: foo-service
          uri: lb://FOO-SERVICE
          predicates:
            - Path=/foo/**
            - Method=GET,POST
          filters:
            - RewritePath=/foo/(?<segment>.*), /$\{segment}
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/