server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: file:///D|/works/spring/msaPrac/configuration

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace,busrefresh
